"""add buiding room ids relation

Revision ID: f4fe8c0cb285
Revises: 0d42b96411a3
Create Date: 2024-09-13 14:50:19.914478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4fe8c0cb285'
down_revision: Union[str, None] = '0d42b96411a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('building_id', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('room_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'room_id')
    op.drop_column('events', 'building_id')
    # ### end Alembic commands ###
