"""change user mail - unique, add systems

Revision ID: 7d6e9937f8a5
Revises: db51b0a2a880
Create Date: 2024-08-22 16:15:39.374665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d6e9937f8a5'
down_revision: Union[str, None] = 'db51b0a2a880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('systems',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=False),
    sa.Column('mail', sa.String(), nullable=False),
    sa.Column('tz', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mail')
    )
    op.drop_table('sytems')
    op.add_column('events', sa.Column('system_id', sa.Integer(), nullable=False))
    op.drop_constraint('events_status_id_fkey', 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'systems', ['system_id'], ['id'])
    op.drop_column('events', 'status_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key('events_status_id_fkey', 'events', 'statuses', ['status_id'], ['id'])
    op.drop_column('events', 'system_id')
    op.create_table('sytems',
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='sytems_pkey')
    )
    op.drop_table('users')
    op.drop_table('systems')
    # ### end Alembic commands ###
