"""change created in statuses history to false and add delete cascade to event status history

Revision ID: 3e235f3f85ee
Revises: 87dc1bd01f05
Create Date: 2024-08-26 12:27:09.991387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e235f3f85ee'
down_revision: Union[str, None] = '87dc1bd01f05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statuses_history', 'created',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_constraint('statuses_history_event_id_fkey', 'statuses_history', type_='foreignkey')
    op.create_foreign_key(None, 'statuses_history', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'statuses_history', type_='foreignkey')
    op.create_foreign_key('statuses_history_event_id_fkey', 'statuses_history', 'events', ['event_id'], ['id'])
    op.alter_column('statuses_history', 'created',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###
