"""add events and priorities

Revision ID: 3e116e52637c
Revises: 988dda2fbf80
Create Date: 2024-08-20 11:21:06.245033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e116e52637c'
down_revision: Union[str, None] = '988dda2fbf80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('priorities',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statuses',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('events', sa.Column('status_id', sa.Integer(), nullable=False))
    op.add_column('events', sa.Column('priority_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'events', 'priorities', ['priority_id'], ['id'])
    op.create_foreign_key(None, 'events', 'statuses', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'priority_id')
    op.drop_column('events', 'status_id')
    op.drop_table('statuses')
    op.drop_table('priorities')
    # ### end Alembic commands ###
