"""change created to created_at

Revision ID: 0d42b96411a3
Revises: 928bea89d212
Create Date: 2024-08-27 00:18:47.315435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d42b96411a3'
down_revision: Union[str, None] = '928bea89d212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statuses_history', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('statuses_history', 'created')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statuses_history', sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('statuses_history', 'created_at')
    # ### end Alembic commands ###
